### ISSUE TITLE
Would you consider adding a license to the repo?

### ISSUE THREAD

**Issue by bimwood** [stewartcelani/autodesk-construction-cloud-backup#1]
Hi Stewart,

This looks like a really interesting project. Would you consider [adding a license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), please - to make it clear how you would like your code to be used?

Many thanks, David

**Comment by stewartcelani** [comment]
Hi David,
I’ve just added the MIT license. Do what you like with it.
This is still used for 150GB~ nightly backups with no issues.
Just FYI if you do take this and do your own thing, I did receive an email from Autodesk today on upcoming changes to their download API to download directly from S3 instead of proxying through their network so I will have to make some changes before end of the year or this will break.
Thanks,
Stewart

**Comment by bimwood** [comment]
That is great, thanks Stewart.
And the info about the upcoming changes - thanks for the heads-up.
Cheers, David
